version: '3.8'

services:
  airflow:
    build: .
    image: parkinson_prediction_airflow
    ports:
      - "8080:8080"   # Expose the Airflow webserver on localhost:8080
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - MLFLOW_TRACKING_URI=file:/opt/airflow/mlruns  # Set tracking URI to a local directory
      - EMAIL=mrudulaacharya18@gmail.com
      - EMAIL_PASSWORD=lhwnkkhmvptmjghx
    volumes:
      - ./dags:/opt/airflow/dags   # Mount DAGs for easy updating
      - ./logs:/opt/airflow/logs   # Optional: log persistence
      - ./raw_data:/opt/airflow/raw_data       # Mount 'raw_data' folder
      - ./motor_assessments:/opt/airflow/motor_assessments  # Mount 'motor_assessments' folder
      - ./outputs:/opt/airflow/outputs # Mount 'output' folder
      - ./models:/opt/airflow/models
      - ./mlruns:/opt/airflow/mlruns # Mount mlruns folder for MLflow tracking
      - ./.dvc:/opt/airflow/.dvc          # Mount DVC metadata folder
      - ./.git:/opt/airflow/.git 
    entrypoint: ["/bin/bash", "/opt/airflow/entrypoint.sh"]